<a href="https://colab.research.google.com/github/charlee/practicalML/blob/master/00_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In this notebook I will explain some basic usage of numpy mainly for machine learning purposes.

In [0]:
# First we need to import numpy, and usually rename it to `np` for convenience
import numpy as np

## Vectors / Matrices

The most useful data structures in machine learning is vectors and matricies.
Usually the input $X$ is provided as a matrix with shape of $(N, d)$, where $N$ is the number of samples
and $d$ is the number of features.
The output is usually a vector $y$ with shape of $(d)$.

**Note**: All the elements in a numpy array must have the same data type. Usually we use `np.float64`.
When creating array with constants, add a decimal point `.` after integer to make it a float. (i.e. `1.` instead of `1`).

In [13]:
# Create vector / matrix
# Conventionally, use uppercase letter for matrix and lowercase letter for vector

# 1-d array => vector
w = np.array([1,2,3])
print("w = ", w)

# 2-d array => matrix
X = np.array([[1.,2.,3.], [4.,5.,6.]])
print("X = ", X)

# shapes
print("w.shape = ", w.shape)
print("X.shape = ", X.shape)

# Data type
print("w.dtype = ", w.dtype)
print("X.dtype = ", X.dtype)

w =  [1 2 3]
X =  [[1. 2. 3.]
 [4. 5. 6.]]
w.shape =  (3,)
X.shape =  (2, 3)
w.dtype =  int64
X.dtype =  float64


In [23]:
# Create zero matrix
X = np.zeros(shape=[3, 4])
print("Zero matrix\n", X)

# Random valued matrix (uniform distribution)
X = np.random.rand(3, 4)
print("Random matrix\n", X)

# 1 matrix
X = np.ones(shape=[3, 4])
print("1 matrix\n", X)

# Matrix with arbitrary value
X = np.empty(shape=[3, 4])
X.fill(3)
print("3 matrix\n", X)

# Identity matrix
X = np.eye(3)
print("Identity(3x3)\n", X)

Zero matrix
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Random matrix
 [[0.72729723 0.1936502  0.53600168 0.92075096]
 [0.3402273  0.43510733 0.96235618 0.38138813]
 [0.61589393 0.66103064 0.10208497 0.41653688]]
1 matrix
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
3 matrix
 [[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]
Identity(3x3)
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Here are some practical examples.

In [0]:
# Test data
X = np.random.rand(100, 4)

# Create weight vector `w` based on input
N, d = X.shape
w = np.zeros(shape=[d])


## Vector / Matrix operations

In [42]:
#######################################
# Vector operations
#######################################

a = np.array([1., 2., 3., 4., 5.])
b = np.array([6., 7., 8., 9., 10.])
print('Vector operations\n-----------------')

# scalar operations
print("Scalar: ", a * 2 + 1)

# element-wise operations
print("a+b=", a + b)
print("a*b=", a * b)

# dot product
print("a.b=", np.dot(a, b))

# L2-norm
print("L2-norm: ||a||=", np.linalg.norm(a))
print("L2-norm square: ||a||^2=", np.square(np.linalg.norm(a)))
print("L2-norm square(alternative): ", np.dot(a, a))

#######################################
# Matrix operations
#######################################

A = np.array([[1., 2., 3.], [4., 5., 6]])
B = np.array([[7., 8.], [9., 10.], [11., 12.]])
C = np.array([[100, 200], [300, 400]])
print('\n\nMatrix operations\n-----------------')
print('A = \n', A)
print('B = \n', B)
print('C = \n', C)

# Transpose
print('A^T = \n', A.T)

# Inverse
print('C^-1 = \n', np.linalg.inv(C))

# Multiplication
print('A * B = \n', np.matmul(A, B))
print('B * A = \n', np.matmul(B, A))


Vector operations
-----------------
Scalar:  [ 3.  5.  7.  9. 11.]
a+b= [ 7.  9. 11. 13. 15.]
a*b= [ 6. 14. 24. 36. 50.]
a.b= 130.0
L2-norm: ||a||= 7.416198487095663
L2-norm square: ||a||^2= 55.0
L2-norm square(alternative):  55.0


Matrix operations
-----------------
A = 
 [[1. 2. 3.]
 [4. 5. 6.]]
B = 
 [[ 7.  8.]
 [ 9. 10.]
 [11. 12.]]
C = 
 [[100 200]
 [300 400]]
A^T = 
 [[1. 4.]
 [2. 5.]
 [3. 6.]]
C^-1 = 
 [[-0.02   0.01 ]
 [ 0.015 -0.005]]
A * B = 
 [[ 58.  64.]
 [139. 154.]]
B * A = 
 [[ 39.  54.  69.]
 [ 49.  68.  87.]
 [ 59.  82. 105.]]


## Matrix slicing, expanding

How to change the dimension of matrices.

In [49]:
# Slice
print('1st column of A = ', A[:,0])
print('2nd row of A = ', A[1])
print('last column of A = ', A[:, -1])
print('1-2 columns of A = \n', A[:, 0:2])

# Split, usually used to extract training input and training labels
input = A[:,:-1]
labels = A[:,-1]
print('input = \n', input)
print('labels = ', labels)

# Add one extra 1's column to A
ones = np.ones(shape=[A.shape[0], 1])
print('Extended A = \n', np.hstack([ones, A]))

1st column of A =  [1. 4.]
2nd row of A =  [4. 5. 6.]
last column of A =  [3. 6.]
1-2 columns of A = 
 [[1. 2.]
 [4. 5.]]
input = 
 [[1. 2.]
 [4. 5.]]
labels =  [3. 6.]
Extended A = 
 [[1. 1. 2. 3.]
 [1. 4. 5. 6.]]
